!!com.appdynamics.cloud.aws.appregistry.ApplicationConfig

controllerAccount: ""
controllerUsername: ""
controllerPassword: ""
controllerHostName: "demo1.saas.appdynamics.com"
controllerPort: 443
controllerSslEnabled: true

jsonFilesDirectory: "/home/ec2-user/environment"

applicationNames:
  - AD-Travel
  - Ecommerce
  - AD-Movie Tickets Core